apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-portal
  namespace: ops
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
